### ISSUE TITLE
Project status?

### ISSUE THREAD

**Issue by DanMcLaughlin** [EpicGamesExt/BlenderTools#714]
Pull requests, issues and questions are piling up. Seems like a reshuffle at Epic has caused a hole here, the plugin is quite mature so shouldn't need lots of support but I'm wondering what level of support we can expect?

**Comment by RWOverdijk** [comment]
I came here to ask something similar (MacOS being broken) and noticed the project got moved, I can't create new issues and the site is broken. Are they dropping the tool? :(

**Comment by wrstldev** [comment]
There's a fork listed now and someone at Epic changed the license on it to MIT. I guess they quietly killed it. Don't know how I'm going to move my data over now.

**Comment by MaSchl74** [comment]
Does that mean I should/can drop UE now (just started learning)? If there's no reliable way to port from Blender, it seems pointless. I wanted to do Archviz walkthroughs and animations, and at the time being I'm rather unsure if getting into UE will save more time than it costs.

**Comment by RWOverdijk** [comment]
> I wanted to do Archviz walkthroughs and animations, and at the time being I'm rather unsure if getting into UE will save more time than it costs.

Idk about the state of this project, but for your specific case there might be better options. Check out USD for example. It's a lot faster to work with. https://www.youtube.com/watch?v=Q9HNRzgRT5E

**Comment by MaSchl74** [comment]
I was also pointed towards Godot, but I'm not sure about the professional looks. So USD it is, though it's still in 4.0 Alpha stage, to my knowledge. Thank you very much!

**Comment by wrstldev** [comment]
> > I wanted to do Archviz walkthroughs and animations, and at the time being I'm rather unsure if getting into UE will save more time than it costs.
> 
> Idk about the state of this project, but for your specific case there might be better options. Check out USD for example. It's a lot faster to work with. https://www.youtube.com/watch?v=Q9HNRzgRT5E

Watching that video now. Thanks.

Having to manually add collisions is brutal. If I have custom animations on objects, so I have to keep manually recreating them every time I tweak my model?

How does the USD importer work compared to the SendToUnreal? It's hard to just upend my entire work flow. Like when I imported tons of objects that need to import around their own origin points, and not the whole file in world space.

Or how I have so many objects that are made up of tons of little meshes parented to an empty object. I've gotten lots of mileage out that feature.

If you know, how does the USD transfer handle animations? Especially with multiple figures in the file?

There's a lot more to this then simply moving data over. That extra functionality we had made a huge difference. Me being able to push an entire city worth of building and parts with auto merged sub-meshes over to UE with auto collisions and proper origins and easily update them over time isn't the same as just being able to open a USD file.

> I was also pointed towards Godot, but I'm not sure about the professional looks. So USD it is, though it's still in 4.0 Alpha stage, to my knowledge. Thank you very much!

Godot only seems like a good option to people who are completely new to game development. Once you have a tiny bit of experience you come to realize that most of the engine is either horrifically broken or poorly implemented and the maintainers are completely full of it. The input functions can't reliably take input. The shader system is broken. The audio player is messed up. The animation player can't reliably play frames. The math functions often return bad or opposite results. The scene editor will quietly shift the positions of your objects over time by small amounts, which will be REAL fun for your arch viz project. Hosing an entire project because you renamed or moved a file is also a common occurrence.

These issues will never be fixed because it's all structured around fundraising endlessly on the promise of fixing them someday. And the money always disappears into a blackhole before fundraising anew again. They even moved their fundraising over to a new platform that lacks transparency and oversight when they were called out over the last fraud incident. When the heat builds up too much they rewrite the renderer to make every everyone forget. :) They fix issues by harassing the bug reporters and fix submitters out of the community.

It doesn't matter how many shiny features an engine promises of none of them work properly, and more importantly none of them work TOGETHER as a hole.

**Thankfully, the 3.6 plugin is still working great for moving static meshes over. You shouldn't have any problems moving your arch wiz models over AFAIK.**

**Comment by MaSchl74** [comment]
OK, that means I can ditch evrything I made after 3.6 and continue working in 3.6? I can see all the issues you pointed out with the empties, though, for that reason, I merged many assets into 1 mesh and by default moved all their origins to the point where they will meet a surface.
I've tried to get sensible input on BA, and atm I really think about ditching all those engines if Blender can't make it into them or the engines are trash and instead use a 360° tour, which seems rather cumbersome to control for the "visitor" imo.

I'm sorry if I somewhat "hijacked" the dev thread, but I really, **really** don't have time to waste. Thanks for all the valued opinions, so I don't waste time with Godot. You never know who recommends these things, possibly devs who "need" funding. That was the right warning, @wrstldev and the correct pointer @DanMcLaughlin. I though Godot looked like an old video game with aliasing even, but as a non-user it's hard to judge.

At least it seems there's some life coming into the thread. I can't even code a pocket calculator or help maintain anything, so I'm sorry if I got things out of order. I can only try to bring awareness to the issue in other places, so maybe some devs will have mercy. I'm willing to pay for a maintained, professional product, btw., the only one that seems to exist at the time being (Blender Datasmith) has left me wondering about a 50% price increase within a couple of weeks and no interest in communicating with potential buyers.

**Comment by RWOverdijk** [comment]
> James and team did an amazing job with this tool and it just needs, probably minimal, support now.

Besides MacOS being broken right now I agree with this and most other points you made. 

My main takeaway is that this might actually be good for the project since it becomes easier to access if you don't have to sign stuff and join epic on github first.

**Comment by DanMcLaughlin** [comment]
I don't know what is being discussed here - the thread did get hijacked. I guess something about doing archviz? Probably better to look elsewhere for that discussion, but yes I see absolutely _zero_ reason Send2UE and Unreal being anything but perfect for that workflow. 

Personal opinion; Mac's are not for professional software development, and certainly not games unless you have to deploy on that platform. Worked in that environment for a long time, if you're in anything AI to games Windows is the only choice, otherwise you're always suffering from lack of tool support, such as Send2UE being broken. 

If we can, otherwise let's close this discussion up thanks.

**Comment by DanMcLaughlin** [comment]
Closed

**Comment by ivanrosadev** [comment]
Butthurt 🤣

**Comment by RWOverdijk** [comment]
> Personal opinion

Imagine being wrong on the internet
